### ISSUE TITLE
issues with commando

### ISSUE THREAD

**Issue by TheRealSpiritJoker** [janiluuk/L4D2_Rage#2]
In getdamage(client) function there is a typo on line 1940, 

if (StrContains(ClientData[client].EquippedGun, "commando", false)!=-1)

should be 

if (StrContains(ClientData[client].EquippedGun, "sniper", false)!=-1)

as it is commando wont get any damage bonus while using  sniper.

also around line 1037 commando bonus damage is being assigned twice.

Damage for commando is assigned per hit ray so a rifle will do say 1x5 while a shotgun will do 10x5 bonus damage.

I added the getdamage() function to give each weapon type it's own damage amount to stop shotgun being so over powered. so you shouldn't add the damage twice. I hardcoded the damage values , you could possibly redo them as convars.

**Comment by janiluuk** [comment]
Good catch!

Will include these in next update.

**Comment by janiluuk** [comment]
Resolved in https://github.com/janiluuk/L4D2_DLRTalents/pull/4

**Comment by janiluuk** [comment]
These changes were merged to new release, Commando's hardcoded multipliers are now configurable and it uses the default only for non-matching items.
